import Link from "next/link";
import { saveProductKnowledge } from "@/app/admin/actions";
import { AdminShell } from "@/components/admin/admin-shell";
import { AdminPagination } from "@/components/admin/admin-pagination";
import { AdminPageHeader, EmptyState, inputClass } from "@/components/admin/admin-widgets";
import { listCmsProductKnowledge } from "@/lib/admin-cms";
import { paginationPageSize, parsePositiveInt } from "@/lib/admin-listing";
import { paginate } from "@/lib/visitor-analytics";

export const dynamic = "force-dynamic";
const join = (items: string[]) => items.join(", ");
type Props = { searchParams: Promise<Record<string, string | string[] | undefined>> };
function value(params: Record<string, string | string[] | undefined>, name: string) { const item = params[name]; return Array.isArray(item) ? item[0] || "" : item || ""; }

export default async function ProductKnowledgePage({ searchParams }: Props) {
  const params = await searchParams;
  const items = await listCmsProductKnowledge();
  const filters = { query: value(params, "query") };
  const page = parsePositiveInt(value(params, "page"));
  const pageSize = paginationPageSize(value(params, "pageSize"));
  const filtered = items.filter((item) => !filters.query || [item.productSlug, item.productSeries, item.primaryKeyword].join(" ").toLowerCase().includes(filters.query.toLowerCase()));
  const paged = paginate(filtered, page, pageSize);
  const selected = items.find((item) => item.id === value(params, "id"));
  return <AdminShell><AdminPageHeader eyebrow="内容管理" title="产品资料" description="维护产品关键词、行业场景和站内关联资料。一次只编辑一条记录，避免长页面操作。" />
    <section className="mt-8 overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><form className="flex gap-3 border-b border-slate-200 bg-slate-50 p-4" method="get"><input name="query" defaultValue={filters.query} className={inputClass} placeholder="搜索产品、系列或关键词" /><select name="pageSize" defaultValue={String(paged.pageSize)} className={inputClass}><option value="20">20 条 / 页</option><option value="25">25 条 / 页</option><option value="50">50 条 / 页</option><option value="100">100 条 / 页</option></select><button className="button button-primary min-h-11" type="submit">筛选</button></form><div className="overflow-x-auto"><table className="min-w-[800px] w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr>{["产品", "系列", "主关键词", "状态", "操作"].map((head) => <th key={head} className="px-5 py-3 font-black">{head}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{paged.items.map((item) => <tr key={item.id}><td className="px-5 py-4 font-bold text-slate-900">{item.productSlug}</td><td className="px-5 py-4 text-slate-700">{item.productSeries}</td><td className="px-5 py-4 text-slate-700">{item.primaryKeyword}</td><td className="px-5 py-4">{item.enabled ? "启用" : "停用"}</td><td className="px-5 py-4"><Link className="rounded-md bg-slate-900 px-3 py-2 text-xs font-black text-white" href={`/admin/product-knowledge?id=${item.id}`}>编辑</Link></td></tr>)}</tbody></table>{!paged.items.length ? <div className="p-5"><EmptyState text="没有符合条件的产品资料。" /></div> : null}</div><AdminPagination pathname="/admin/product-knowledge" query={{ ...filters, pageSize: paged.pageSize }} page={paged.page} totalPages={paged.totalPages} total={paged.total} pageSize={paged.pageSize} label="资料" /></section>
    {selected ? <form action={saveProductKnowledge} className="mt-8 grid gap-4 rounded-xl border border-slate-200 bg-white p-6 shadow-sm md:grid-cols-2"><input type="hidden" name="id" value={selected.id} /><div className="md:col-span-2"><h2 className="text-xl font-black text-slate-950">编辑：{selected.productSlug}</h2><p className="mt-1 text-sm text-slate-500">{selected.productSeries}</p></div><label className="text-sm font-bold">主关键词<input name="primaryKeyword" defaultValue={selected.primaryKeyword} className={`${inputClass} mt-2 w-full`} /></label><label className="text-sm font-bold">次关键词<input name="secondaryKeywords" defaultValue={join(selected.secondaryKeywords)} className={`${inputClass} mt-2 w-full`} /></label><label className="text-sm font-bold">规格关键词<input name="specificationKeywords" defaultValue={join(selected.specificationKeywords)} className={`${inputClass} mt-2 w-full`} /></label><label className="text-sm font-bold">行业<input name="industries" defaultValue={join(selected.industries)} className={`${inputClass} mt-2 w-full`} /></label><label className="text-sm font-bold">应用场景<input name="scenarios" defaultValue={join(selected.scenarios)} className={`${inputClass} mt-2 w-full`} /></label><label className="text-sm font-bold">客户痛点<input name="buyerPainPoints" defaultValue={join(selected.buyerPainPoints)} className={`${inputClass} mt-2 w-full`} /></label><label className="text-sm font-bold md:col-span-2">解决方案<textarea name="solutionSummary" defaultValue={selected.solutionSummary} rows={3} className={`${inputClass} mt-2 w-full`} /></label><label className="text-sm font-bold">客户收益<input name="buyerBenefits" defaultValue={join(selected.buyerBenefits)} className={`${inputClass} mt-2 w-full`} /></label><label className="text-sm font-bold">关联产品路径<input name="relatedProductSlugs" defaultValue={join(selected.relatedProductSlugs)} className={`${inputClass} mt-2 w-full`} /></label><label className="text-sm font-bold">关联应用页<input name="relatedApplicationSlugs" defaultValue={join(selected.relatedApplicationSlugs)} className={`${inputClass} mt-2 w-full`} /></label><label className="text-sm font-bold">禁止使用的夸大表述<input name="prohibitedClaims" defaultValue={join(selected.prohibitedClaims)} className={`${inputClass} mt-2 w-full`} /></label><label className="flex items-center gap-2 text-sm font-bold md:col-span-2"><input name="enabled" type="checkbox" defaultChecked={selected.enabled} /> 启用此产品资料</label><button className="button button-primary justify-self-start md:col-span-2" type="submit">保存资料</button></form> : null}
  </AdminShell>;
}
